name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: cache npm modules
        uses: actions/cache@v2
        with:
          key: npm
          path: node_modules
      - name: install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
